site_name: Belarus Transparency
site_url: https://belarus-transparency.org/
use_directory_urls: true
site_description: Исследовательский проект о динамике беларуской оппозиции
site_author: Belarus Transparency Project

theme:
  name: material
  custom_dir: overrides
  language: ru
  font: false
  logo: assets/logo-horizontal-ru-light.svg
  favicon: assets/favicon.svg
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: bt/theme-toggle-light
        name: Тёмная тема
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: bt/theme-toggle-dark
        name: Светлая тема
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - Расследования: investigations/index.md
  - Персоналии: persons/index.md
  - Организации: organizations/index.md
  - События: events/index.md

plugins:
  - search:
      lang: ru
  - macros:
      module_name: main  

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - toc:
      permalink: true

extra:
    alternate:
    - name: Русский
      link: /
      lang: ru
    - name: English
      link: /en/
      lang: en
    generator: false
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/belarustransparency