site_name: Belarus Transparency
site_url: https://belarus-transparency.org/
use_directory_urls: true
site_description: Исследовательский проект о динамике беларуской оппозиции
site_author: Belarus Transparency Project

theme:
  name: material
  language: ru
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Тёмная тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Светлая тема
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.indexes  # ← добавить, чтобы index.ru.md в папках работали как обложки разделов

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: ru
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ru
          default: true
          name: Русский
          build: true
        - locale: en
          name: English
          build: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/belarustransparency